---
abstract: 'Perl extension for recursively copying files and directories'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Path::Tiny: '0'
  Test::Deep: '0'
  Test::Fatal: '0'
  Test::File: '0'
  Test::More: '0.88'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Copy-Recursive
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  File::Copy: '0'
  File::Glob: '0'
  File::Spec: '0'
  File::Temp: '0'
  Path::Tiny: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::File: '0'
  Test::More: '0'
  Test::Warn: '0'
version: '0.45'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-Copy-Recursive
  repository: https://github.com/drmuey/p5-File-Copy-Recursive.git
version: '0.44'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
